base_url = "https://eiwblog.pages.dev/"
title = "Wilson Moura"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["themes/serene/highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
sections = [
  { name = "home", path = "/", is_external = false },
  { name = "about", path = "/about", is_external = false }
]
blog_section_path = "/posts"

back_link_text = "Back"
force_theme = "light"

footer_copyright = "© 2025 Wilson Moura"
footer_credits = true

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"
